"""Generate a single Markdown report for Long: 24 QTLs × top-K candidates +
all cross-QTL overlap findings. Designed to be readable top-to-bottom, with
the most striking discoveries up front.

Output: output/qtl_report.md (~50 KB; one read sits within a phone screen scroll).

Run:
  python src/build_qtl_report.py
  python src/build_qtl_report.py --topk 15
"""
from __future__ import annotations
import argparse
import json
import sqlite3
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from flyatlas.qtl_rank import rank_qtl, list_qtls
from flyatlas.qtl_overlap import coord_overlap, shared_genes


DEFAULT_DB = ROOT / "tools" / "atlas.db"
REPORT_OUT = ROOT / "output" / "qtl_report.md"


QUADRANT_GLYPH = {
    "STRONG":        "✓",
    "NOVEL_LEAD":    "⚠",
    "LIKELY_NOT":    "✗",
    "CANT_RULE_OUT": "?",
}


def fmt_bp(n: int) -> str:
    if n is None: return "—"
    if n >= 1_000_000:
        return f"{n/1_000_000:.2f} Mb"
    return f"{n:,} bp"


def fmt_int(n: int) -> str:
    return f"{n:,}" if n is not None else "—"


def write_headline(f, overlaps_cross_class: list[dict]) -> None:
    """Top of the report: the discoveries Long should read first."""
    f.write("# fly-distill × QTL_summary.md — automated candidate report\n\n")
    f.write("**Source data**: 24 QTLs from 5 published studies (`data/QTL_summary.md`).  \n")
    f.write("**Atlas version**: v1.3 (14,019 *D. melanogaster* protein-coding genes, "
            "Gemini-embedded, MGI+HPO+OMIM cross-species).  \n")
    f.write("**Generated by**: `src/build_qtl_report.py`  \n\n")
    f.write("---\n\n")
    f.write("## Headline findings\n\n")
    f.write("These are the **cross-drug-family QTL overlaps** — pairs of independent "
            "studies whose mapped intervals share genome space and therefore likely "
            "share a causal gene. Cross-family overlap is the strongest fly-distill "
            "signal because it indicates a gene affecting **multiple stress responses**, "
            "not just one drug's idiosyncrasy.\n\n")
    if not overlaps_cross_class:
        f.write("*(No cross-class overlaps found.)*\n\n")
    else:
        f.write(f"| QTL A | QTL B | Chr | Shared region | Overlap | Genes |\n")
        f.write(f"|---|---|---|---|---|---|\n")
        for o in overlaps_cross_class:
            f.write(f"| `{o['qtl_a']}` ({o['drug_a']}) "
                    f"| `{o['qtl_b']}` ({o['drug_b']}) "
                    f"| {o['chr']} "
                    f"| {o['shared_start_r6']:,}–{o['shared_end_r6']:,} (r6) "
                    f"| {fmt_bp(o['overlap_bp'])} "
                    f"| {o['n_genes_in_shared_region']} |\n")
    f.write("\n")


def write_overlap_deep_dive(f, db_path: str, overlap: dict, topk: int = 10) -> None:
    """Deep-dive into one specific overlap with the actual shared gene list."""
    a_id = overlap["qtl_a"]; b_id = overlap["qtl_b"]
    f.write(f"### {a_id} × {b_id} ({overlap['drug_a']} × {overlap['drug_b']})\n\n")
    f.write(f"- **Shared region (r6)**: `{overlap['chr']}:{overlap['shared_start_r6']:,}–{overlap['shared_end_r6']:,}`  \n")
    f.write(f"- **Overlap**: {fmt_bp(overlap['overlap_bp'])}  \n")
    f.write(f"- **Phenotype A**: {overlap['phenotype_a']}  \n")
    f.write(f"- **Phenotype B**: {overlap['phenotype_b']}  \n\n")

    detail = shared_genes(db_path, a_id, b_id, topk=topk)
    if "error" in detail or not detail.get("genes"):
        f.write("*(no shared genes resolvable in atlas)*\n\n")
        return
    f.write("**Top shared candidates (by annotation depth):**\n\n")
    f.write("| rank | symbol | n_bullets | n_refs | n_pubs |\n")
    f.write("|---:|---|---:|---:|---:|\n")
    for i, g in enumerate(detail["genes"], 1):
        f.write(f"| {i} | `{g['symbol']}` | {g['n_bullets']} | {g['n_refs']} | "
                f"{g['n_pubs_total'] or 0} |\n")
    f.write("\n")


def write_per_qtl(f, db_path: str, qtl_id: str, topk: int) -> None:
    """One QTL's full candidate list."""
    result = rank_qtl(db_path, qtl_id, topk=topk)
    if "error" in result:
        f.write(f"### `{qtl_id}` — *(error: {result['error']})*\n\n")
        return
    if "warning" in result and not result.get("candidates"):
        q = result.get("qtl") or {}
        f.write(f"### `{qtl_id}` — {q.get('study_drug','?')} on {q.get('chr','?')}\n\n")
        f.write(f"> {q.get('phenotype','?')}\n\n")
        f.write(f"*(skipped: {result['warning']} — this QTL spans a region not "
                f"resolvable in the current atlas; cross-arm intervals like "
                f"`{q.get('chr','?')}` need manual coordinate handling)*\n\n")
        return
    q = result["qtl"]
    s = result["summary"]
    f.write(f"### `{qtl_id}` — {q['study_drug']} on {q['chr']}\n\n")
    f.write(f"> {q['phenotype']}\n\n")
    f.write(f"- **Interval (r6)**: `{q['chr']}:{fmt_int(q.get('start_r6'))}–{fmt_int(q.get('end_r6'))}` "
            f"({fmt_bp((q.get('end_r6') or 0) - (q.get('start_r6') or 0))})  \n")
    if q.get("release_orig") == "r5":
        f.write(f"- **Native (r5)**: `{q['chr']}:{fmt_int(q.get('start_r5'))}–{fmt_int(q.get('end_r5'))}` "
                f"(intervals lifted via shared FBgn coordinates from FB2026_01 + FB2014_01)  \n")
    if q.get("neg_log_p"):
        f.write(f"- **Significance**: −log₁₀(P) = {q['neg_log_p']}  \n")
    if q.get("h2"):
        f.write(f"- **Heritability**: {q['h2']}  \n")
    if q.get("pmc_url"):
        f.write(f"- **Source**: [{q['pmc_url'].rstrip('/').split('/')[-1]}]({q['pmc_url']})  \n")
    f.write(f"- **Total genes in interval**: {s['total_in_interval']}  \n")
    by_q = s["by_quadrant"]
    f.write(f"- **Quadrants**: "
            f"✓ STRONG **{by_q['STRONG']}** · "
            f"⚠ NOVEL_LEAD **{by_q['NOVEL_LEAD']}** · "
            f"✗ LIKELY_NOT **{by_q['LIKELY_NOT']}** · "
            f"? CANT_RULE_OUT **{by_q['CANT_RULE_OUT']}**\n\n")

    if not result["candidates"]:
        f.write("*(no candidates ranked)*\n\n")
        return
    f.write("| rank | symbol | quadrant | evidence | quality | n_b | n_r | n_p |\n")
    f.write("|---:|---|---|---:|---:|---:|---:|---:|\n")
    for i, g in enumerate(result["candidates"], 1):
        glyph = QUADRANT_GLYPH[g["quadrant"]]
        f.write(f"| {i} | `{g['symbol']}` | {glyph} {g['quadrant']} | "
                f"{g['evidence']:.2f} | {g['quality']:.2f} | "
                f"{g['n_bullets']} | {g['n_refs']} | {g['n_pubs_total'] or 0} |\n")
    f.write("\n")


def write_scoring_methodology(f) -> None:
    f.write("## Scoring methodology (the 2D Long framework)\n\n")
    f.write("Each candidate gene gets **two independent scores**, deliberately not "
            "combined into one number — because (per Long's email) a stub gene with "
            "no annotation is fundamentally different from a well-studied gene with no "
            "annotation. *Absence of evidence is not evidence of absence.*\n\n")
    f.write("**Evidence score (0–1)**: Gemini `gemini-embedding-2` cosine similarity "
            "between the phenotype description (e.g. *\"Adult female longevity on 1% "
            "caffeine\"*) and each gene's pre-computed embedding (built from its "
            "FlyBase summary + structured phenotype bullets + cross-species ortholog "
            "phenotype context).\n\n")
    f.write("**Quality score (0–1)**: composite of how well-studied the gene is, "
            "computed from per-gene aggregates:\n\n")
    f.write("    quality = 0.30 · log₁(n_bullets)/log₁(30)\n")
    f.write("            + 0.25 · log₁(n_refs)/log₁(25)\n")
    f.write("            + 0.20 · log₁(n_pubs_total)/log₁(500)\n")
    f.write("            + 0.10 · I[has human HPO phenotypes]\n")
    f.write("            + 0.10 · I[has mouse MGI knockout phenotypes]\n")
    f.write("            + 0.05 · I[has OMIM disease link]\n")
    f.write("            − 0.15 · I[n_bullets ≤ 3, i.e. stub]\n\n")
    f.write("Quadrants (cutoffs: evidence ≥ 0.55, quality ≥ 0.50):\n\n")
    f.write("| Quadrant | Meaning | Long's interpretation |\n")
    f.write("|---|---|---|\n")
    f.write("| ✓ **STRONG** | high evidence + well-annotated | Top-priority follow-up |\n")
    f.write("| ⚠ **NOVEL_LEAD** | high evidence + sparsely annotated | Worth functional experiment — under-studied gene with strong semantic match |\n")
    f.write("| ✗ **LIKELY_NOT** | low evidence + well-annotated | Can rule out with confidence — heavily studied gene not linked to this phenotype |\n")
    f.write("| ? **CANT_RULE_OUT** | low evidence + sparsely annotated | Keep — no positive signal, but no evidence to exclude either |\n\n")
    f.write("---\n\n")


def write_coordinate_provenance(f) -> None:
    f.write("## Coordinate provenance\n\n")
    f.write("Long correctly noted (2026-05-19 email) that the chemo papers report "
            "r5 (BDGP5 / FB2014_01) coordinates while newer studies use r6 "
            "(BDGP6 / FB2026_01).\n\n")
    f.write("Our atlas stores **both r5 and r6 coordinates per FBgn** by joining "
            "the FlyBase authoritative `gene_map_table` from both releases:\n\n")
    f.write("- **r6**: https://ftp.flybase.org/releases/current/precomputed_files/genes/gene_map_table_fb_2026_01.tsv.gz\n")
    f.write("- **r5**: https://s3ftp.flybase.org/releases/FB2014_01/precomputed_files/genes/gene_map_table_fb_2014_01.tsv.gz\n\n")
    f.write("Three-way FBgn coverage:\n\n")
    f.write("| set | size | % of atlas |\n")
    f.write("|---|---:|---:|\n")
    f.write("| Atlas FBgns | 14,019 | 100.0% |\n")
    f.write("| Atlas ∩ r6 gene_map_table | 13,986 | 99.8% |\n")
    f.write("| Atlas ∩ r5 gene_map_table | 13,569 | 96.8% |\n")
    f.write("| Atlas FBgns missing from BOTH | 33 | 0.2% |\n")
    f.write("| Atlas FBgns missing from r5 only (post-2014 IDs) | 450 | 3.2% |\n\n")
    f.write("For r5-native QTL intervals, we map to r6 by looking up the genes in "
            "the r5 interval and taking the (chr, min(start_r6), max(end_r6)) of "
            "the matched FBgn set. This is exact per-FBgn lift, not chain-file "
            "interpolation.\n\n")
    f.write("---\n\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(DEFAULT_DB))
    ap.add_argument("--out", default=str(REPORT_OUT))
    ap.add_argument("--topk", type=int, default=20)
    args = ap.parse_args()

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # 1. Cross-QTL overlap
    overlaps = coord_overlap(args.db)
    cross_class = [o for o in overlaps if o["is_cross_drug_family"]]

    print(f"Found {len(overlaps)} overlapping QTL pairs ({len(cross_class)} cross-class).")
    print(f"Ranking 24 QTLs ...")

    with open(out_path, "w") as f:
        # Headline at top
        write_headline(f, cross_class)

        # Cross-class deep dives
        f.write("## Cross-class overlap deep dives\n\n")
        f.write("Each shared region below contains genes that *one independent study* "
                "mapped as a candidate for one stress, and *another independent study* "
                "for a different stress. These genes are inherently strong candidates "
                "for **general cellular response mechanisms**.\n\n")
        for o in cross_class:
            write_overlap_deep_dive(f, args.db, o, topk=10)

        f.write("---\n\n")

        # Same-class overlaps (less novel but still useful)
        same_class = [o for o in overlaps if not o["is_cross_drug_family"]]
        if same_class:
            f.write("## Same-class overlap (expected biology, sanity check)\n\n")
            for o in same_class:
                write_overlap_deep_dive(f, args.db, o, topk=5)
            f.write("---\n\n")

        # Methodology
        write_scoring_methodology(f)
        write_coordinate_provenance(f)

        # Per-QTL
        f.write("## Per-QTL candidate rankings\n\n")
        qtls = list_qtls(args.db)
        # Sort: r6 native first (more confident intervals), then by significance
        qtls.sort(key=lambda q: (q["release_orig"] == "r5",  # r6 first
                                 -(q["neg_log_p"] or 0)))   # high p first

        f.write("Ordered by genome release (r6-native first), then by significance.\n\n")
        for q in qtls:
            write_per_qtl(f, args.db, q["id"], topk=args.topk)
            print(f"  ranked {q['id']}", flush=True)

        f.write("---\n\n")
        f.write("## Re-running this report\n\n")
        f.write("```bash\n")
        f.write("python src/build_qtl_report.py --topk 20\n")
        f.write("```\n")
        f.write("Atlas: https://github.com/sgaofen/fly-distill v1.3+r5coords  \n")
        f.write(f"Report generated against atlas.db schema version with chr/chr_r5 columns.\n")

    n_bytes = out_path.stat().st_size
    print(f"\nWrote {out_path} ({n_bytes:,} bytes)")


if __name__ == "__main__":
    main()
