"""Compile per-gene distillation outputs into one clean Markdown doc for Long.

Output: snapshot + cross-species + bullets per gene. Nothing else.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def load_rows():
    """Load each gene that has a bullets.json output."""
    import sys as _sys
    _sys.path.insert(0, str(Path(__file__).resolve().parent))
    from gene_list import GENES
    rows = []
    for g in GENES:
        bp = ROOT / "output" / g["fbgn"] / "bullets.json"
        if not bp.exists():
            continue
        bullets = json.loads(bp.read_text())
        bundle_path = ROOT / "data" / "cache" / g["fbgn"] / "bundle.json"
        bundle = json.loads(bundle_path.read_text()) if bundle_path.exists() else {}
        rows.append({
            "gene": g,
            "bullets": bullets,
            "h_orth": bundle.get("human_ortholog_data", []),
            "m_orth": bundle.get("mouse_ortholog_data", []),
        })
    return rows


def fmt_bullet(b: dict) -> str:
    cat = b.get("category") or "?"
    phen = b.get("phenotype") or ""
    ev = b.get("evidence") or ""
    direction = b.get("direction") or ""
    dir_tag = f" — {direction}" if direction and direction not in ("unknown", "either", "-") else ""
    return f"- **[{cat}]** {phen}{dir_tag}\n  - *source:* {ev}"


def md_for_gene(row: dict) -> str:
    g = row["gene"]
    b = row["bullets"]
    out = []
    sym = b.get("symbol") or g["symbol"]
    out.append(f"## {sym}  *({g['note']})*\n")
    out.append(f"**Snapshot.** {b.get('summary', '')}\n")

    cs = b.get("cross_species") or {}
    h_d = cs.get("human_disease") or []
    m_p = cs.get("mouse_phenotype") or []
    if h_d:
        out.append(f"**Human disease links (via ortholog):** {' · '.join(h_d)}")
    if m_p:
        out.append(f"**Mouse phenotype (via ortholog):** {' · '.join(m_p)}")
    if not h_d and not m_p:
        out.append("**Cross-species:** no clean disease/phenotype link in the data.")

    # ortholog list
    h_orth = row.get("h_orth", [])
    m_orth = row.get("m_orth", [])
    if h_orth or m_orth:
        parts_o = []
        if h_orth:
            parts_o.append("human " + ", ".join(f"{o['symbol']} ({o['diopt_score']}/{o['diopt_max']})" for o in h_orth))
        if m_orth:
            parts_o.append("mouse " + ", ".join(f"{o['symbol']} ({o['diopt_score']}/{o['diopt_max']})" for o in m_orth))
        out.append(f"**Top orthologs used:** {' · '.join(parts_o)}")

    out.append("\n**Bullets:**\n")
    for bb in b.get("bullets", []):
        out.append(fmt_bullet(bb))
    return "\n".join(out)


def main():
    rows = load_rows()
    parts = []
    parts.append("# Fly gene distillation — 6 sample genes\n")
    parts.append("For each gene below: a one-paragraph snapshot, the human/mouse disease links the "
                 "ortholog data implies, and ~25 phenotype-anchored bullets each with a source "
                 "pointer back into the FlyBase / FBrf paper / ortholog data it came from. "
                 "Generated by GLM-5.1 in one API call per gene.\n")
    for r in rows:
        parts.append("\n---\n")
        parts.append(md_for_gene(r))
    out_path = ROOT / "output" / "report_for_long.md"
    out_path.write_text("\n".join(parts))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
